/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -c TabManagerInterface -p TabManagerInterface.h: BrowserService.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef TABMANAGERINTERFACE_H_1305164883
#define TABMANAGERINTERFACE_H_1305164883

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.meego.browser.BrowserService
 */
class TabManagerInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.meego.browser.BrowserService"; }

public:
    TabManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~TabManagerInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> closeTab(int index)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(index);
        return asyncCallWithArgumentList(QLatin1String("closeTab"), argumentList);
    }

    inline QDBusPendingReply<int> getCurrentTabIndex()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getCurrentTabIndex"), argumentList);
    }

    inline QDBusPendingReply<> removeBookmark(const QString &id)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(id);
        return asyncCallWithArgumentList(QLatin1String("removeBookmark"), argumentList);
    }

    inline QDBusPendingReply<> removeUrl(const QString &url)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(url);
        return asyncCallWithArgumentList(QLatin1String("removeUrl"), argumentList);
    }

    inline QDBusPendingReply<> showBrowser(const QString &mode, const QString &target)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(mode) << qVariantFromValue(target);
        return asyncCallWithArgumentList(QLatin1String("showBrowser"), argumentList);
    }

    inline QDBusPendingReply<> updateCurrentTab()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("updateCurrentTab"), argumentList);
    }

    inline QDBusPendingReply<> viewItem(const QString &url)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(url);
        return asyncCallWithArgumentList(QLatin1String("viewItem"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void bookmarkRemoved(qlonglong id);
    void bookmarkUpdated(qlonglong id, const QString &url, const QString &title, const QString &faviconUrl);
    void browserClosed();
    void browserLaunched();
    void faviconUpdated(const QString &url);
    void tabInfoUpdated(int index);
    void tabListUpdated();
    void thumbnailUpdated(const QString &url);
    void urlRemoved(const QString &url);
    void urlVisited(qlonglong id, const QString &url, const QString &title, const QString &faviconUrl);
};

#endif
